### ISSUE TITLE
Something is wrong with fromStringAs method

### ISSUE THREAD

**Issue by martyall** [rowtype-yoga/purescript-js-bigints#14]
Something is wrong with `fromStringAs` vs `fromString`. `fromStringAs` seems to be unable to parse anything over the 32bit int limit

```
> import JS.BigInt as BI                                       
> BI.fromString  "0x7FFFFFFF"
(Just 2147483647)

> BI.fromString  "0x8FFFFFFF"
(Just 2415919103)

> BI.fromStringAs  hexadecimal "7FFFFFFF"
(Just 2147483647)

> BI.fromStringAs  hexadecimal "8FFFFFFF"
Nothing
```

Here is the relevant section of JS source:

```javascript
        if (pattern.test(s)) {
          var size = 10;
          var factor = BigInt(radix ** size);
          var r = 0n

          for (var i = 0; i < s.length; i += size) {
            var n = parseInt(s.slice(i, i + size), radix);

            // check for NaN
            if ((n | 0) !== n) {
              return nothing;
            }

            r = r * factor + BigInt(n);
          }

          return just(r);
        } else {
          return nothing;
        }
      };
    };
```

It seems like if you hard code the slice window size as 10, in this case you are potentially trying to convert 
`8FFFFFFF` into a JS int before arithmetically folding it in to the accumulator, which is why it's failing.

At the very least we should be able to accommodate all of the radixes in `Data.Int` that have names, and in the current representation I believe `hexadecimal` and `base36` are broken. I feel like the move here is to set the `size = 6` in the above code,  sacrificing speed in some cases for correct behavior in all. The reason for 6 is that 

```
2147483647 (base 10) == ZIK0ZJ (base 36)
```

**Comment by iostat** [comment]
So it was weird to me that the cap seems to be around 32-bit MAX_VALUE, when `Number.MAX_SAFE_INTEGER` is `2^53-1`. `8FFFFFFF` fits perfectly fine into a regular `Number`: 

<img width="300" alt="image" src="https://github.com/purescript-contrib/purescript-js-bigints/assets/2927187/bbb10b4b-b6b2-4e5a-9f9a-980d179c1e9e">

I think the issue is in the NaN check:
```javascript
// check for NaN
if ((n | 0) !== n) {
  return nothing;
}
```

[Per MDN for bitwise OR](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_OR), if you're doing bitwise OR and one or both of your operands aren't BigInts, they'll get coerced down to 32-bit values. This is pretty easy to demonstrate:
<img width="317" alt="image" src="https://github.com/purescript-contrib/purescript-js-bigints/assets/2927187/2869049b-c1e9-45da-83ca-886388b1b013">

So dropping the window down to 6 would work around the issue, since you'll never exceed 32BIT_MAX, at the cost of speed as @martyall notes. Alternatively, reworking the NaN check a little bit, lets you keep the 10-char window.
[Per MDN for parseInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt#return_value), you shouldn't ever get anything besides a (integer) Number or `NaN`, so the check could simply be.
```javascript
// check for NaN
if (n === NaN) {
  return nothing;
}
```

**Comment by martyall** [comment]
I have actually tried both of the solutions proposed on this thread and neither was able to pass this test

https://github.com/martyall/purescript-js-bigints/pull/1/files#diff-71732b478b4808898d86c8591ad7ab46d8122c1e4facec4a9151ac49efba905dR83-R86

Here is evidence of your master branch failing: https://github.com/martyall/purescript-js-bigints/actions/runs/6154957373/job/16701107739
