### ISSUE TITLE
rename the module to Data.BigInt

### ISSUE THREAD

**Issue by gbagan** [rowtype-yoga/purescript-js-bigints#6]
Hi,

since purescript-bigints is now deprecated, I think it could be a good idea to rename the module to Data.BigInt (instead of JS.BigInt)
It would make the naming more consistent with that of other modules.
Actually, I think there is no reason to use the prefix "JS"
What do you think?

**Comment by gbagan** [comment]
Or maybe Data.Integer if we want to be closer to Haskell.

**Comment by sigma-andex** [comment]
Who would want to be closer to Haskell? 😆

I think `JS.BigInt` fits better, because this is JS specific. There are other backends (Erlang, Chez) which do not support this. If I understood @garyb correctly then the idea in general is to go to `purescript-js-*` packages for JS specific stuff with `JS.*` namespaces, and keeping the other packages platform independent.

**Comment by gbagan** [comment]
Ok, I understand the point of view.
I close the issue.
